name: Node.js CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
    - run: npm run build --if-present
      env:
        REACT_APP_COGNITO_USERPOOL_ID: ${{ secrets.REACT_APP_COGNITO_USERPOOL_ID }}
        REACT_APP_COGNITO_APP_CLIENT_ID: ${{ secrets.REACT_APP_COGNITO_APP_CLIENT_ID }}
        REACT_APP_API_BASE: https://api.geolonia.com
        REACT_APP_APP_API_BASE: https://api.app.geolonia.com
        REACT_APP_GEOSEARCH_API_BASE: https://gesearch.example.geolonia.com
        REACT_APP_STAGE: dev
    
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        # Build directory to deploy
        build_dir: build
