name: Node.js CI

on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        env:
          CI: true
      - run: npm run build:ci
        env:
          REACT_APP_COGNITO_USERPOOL_ID: ${{ secrets.REACT_APP_COGNITO_USERPOOL_ID }}
          REACT_APP_COGNITO_APP_CLIENT_ID: ${{ secrets.REACT_APP_COGNITO_APP_CLIENT_ID }}
          REACT_APP_API_BASE: https://api.geolonia.com
          REACT_APP_APP_API_BASE: https://api.app.geolonia.com
          REACT_APP_GEOSEARCH_API_BASE: https://gesearch.example.geolonia.com
          REACT_APP_STAGE: dev
      - run: npm run cname
        env:
          CNAME: dev.app.geolonia.com

      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: build
          GH_PAT: ${{ secrets.GH_PAT }}
